blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
]

poll/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'poll'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),


]

wisdom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),
    path('poll/',include('poll.urls')),
]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    image = models.ImageField(upload_to ='img',null=True)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()



    def __str__(self):
        return self.title

poll/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
    	return self.pub_date >= timezone.now()-datetime.timedelta(days=1) #ask this ????



    def __str__(self):
        return self.question_text




class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text','image')

blog/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Post
from django.utils import timezone
from .forms import PostForm

 


# Create your views here.
def post_list(request):

	posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	return render(request, 'blog/post_list.html', {"posts" : posts })
	

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post}) 


def post_new(request):
	if request.method == "POST":
		form = PostForm(request.POST,request.FILES)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.published_date = timezone.now()
			post.save()
			return redirect('blog:post_detail', pk=post.pk)
    
	else:

	    form = PostForm()
	return render(request, 'blog/post_edit.html', {'form': form})



def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST,request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

poll/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
#from django.template import loader
from .models import Question,Choice


# Create your views here.

def index(request):
	latest_question_list = Question.objects.order_by('-pub_date')[:6]
	context = {'latest_question_list': latest_question_list}
	return render(request, 'poll/index.html', context)

def detail(request, question_id):
	try:
		question = Question.objects.get(pk=question_id)
	except Question.DoesNotExist:
		raise Http404("Question does not exist")
	return render(request, 'poll/detail.html', {'question': question})
	

def results(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	return render(request, 'poll/results.html', {'question': question})
    

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'poll/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('poll:results', args=(question.id,)))

blog/templates/blog/base.html
{% load static %}
<html>
    <head>
        <title>Blog World</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>
    <body>
        <body>
    <div class="page-header">
        {% if user.is_authenticated %}
        <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
        {% endif %}
        <h1><a href="{% url 'blog:post_list' %}">Blog World</a>&nbsp;&nbsp;&nbsp;&#124;<a href="{% url 'poll:index' %}" >  Poll app</a></h1>

    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
</body>
    </body>
</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}
        <a class="btn btn-default" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        <h2>{{ post.title }}</h2>
        <p>{{ post.text|linebreaksbr }}</p>
        <img src="{{ post.image.url}}" height="250" width="400">
    </div>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h2>New post</h2>
    <form method="POST" class="post-form" enctype="multipart/form-data" >{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block content %}
    {% for post in posts %}
    	
        <div class="post">
            <div class="date">
                {{ post.published_date }}
            </div>
            <h2><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
            <p>{{ post.text|linebreaksbr }}</p>
            {% if post.image %}
            <img src="{{ post.image.url }}" height="250" width="400">
            {% endif %}
        </div>
        
    {% endfor %}
{% endblock %}

poll/templates/poll/detail.html
{% extends 'poll/index.html'%}

{% block content %}
<h1>{{ question.question_text }}</h1>

	{% if error_message %}
	<p>
		<strong>{{ error_message }}</strong>
	</p>
	{% endif %}

		<form action="{% url 'poll:vote' question.id %}" method="post">
			{% csrf_token %}
			{% for choice in question.choice_set.all %}
    		<h2><input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"></h2>
    		<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
			{% endfor %}
			<input type="submit" value="Vote">
		</form>
{% endblock %}

poll/templates/poll/index.html
{% load static %}
<html>
    <head>
        <title>Blog World</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/poll.css' %}">
    </head>
    <body>
        
    <div class="page-header">
        
        <h1><a href="{% url 'blog:post_list' %}">Blog World</a>&nbsp;&nbsp;&nbsp;&#124;<a href="{% url 'poll:index' %}" >  Poll app</a></h1>

    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            {% block content %}
            {% if latest_question_list %}
            <ul>
            {% for question in latest_question_list %}
                <h2><li><a href="{% url 'poll:detail' question.id %}">{{ question.question_text }}</a></li></h2>
            {% endfor %}
            </ul>
            {% else %}
                <p>No polls are available.</p>
            {% endif %}
            {% endblock %}
            </div>
        </div>
    </div>

    </body>
</html>

poll/templates/poll/results.html
{% extends 'poll/index.html' %}

{% block content %}
<h1>{{ question.question_text }}</h1>

	<ul>
		{% for choice in question.choice_set.all %}
    	<li ><h4>{{ choice.choice_text }} : {{ choice.votes }} vote{{ choice.votes|pluralize }}</h4></li>
		{% endfor %}
	</ul>

	<h4><a href="{% url 'poll:detail' question.id %}">Vote again?</a></h4>

{% endblock %}